web:
  restart: always
  build: ./web
  ports:
    - "5000:5000"
  expose:
    - "5000"
  links:
    - mongo:mongo
  volumes:
    - .:/usr/src/app
  env_file: .env
  command: uwsgi --ini /usr/src/app/web/setlist_visualizer.ini --pythonpath /usr/src/app/web/

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

mongo:
  restart: always
  hostname: mongo_host
  image: mongo:latest
  volumes:
    - /Users/data/db:/data/db
  ports:
    - "27017:27017"