web:
  restart: always
  build: ./web
  ports:
    - "5000:5000"
  expose:
    - "5000"
  links:
    - mongo:mongo
  volumes:
    - ~/Github/setlist_visualizer:/usr/src/app
  env_file: .env
  command: uwsgi --ini /usr/src/app/web/setlist_visualizer.ini --pythonpath /usr/src/app/web/

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

mongo:
  restart: always
  image: mongo:latest
  volumes:
    - /var/data/mongo
  ports:
    - "5432:5432"